### ISSUE TITLE
[Suggestion] Please make a simple example on vanilla JS and some explaination

### ISSUE THREAD

**Issue by thednp** [PitPik/colorPicker#19]
I'm trying to implement this in my project and found it a bit difficult to work with.

I was expecting to link ONE js file and ONE css file, give it an initialization and I'm good, but I'm getting some errors, I have no idea

<pre>
colorPicker.js?ver=4.2.2:17 Uncaught TypeError: Cannot read property 'style' of null
</pre>

**Comment by PitPik** [comment]
Hi @thednp 
it is actually as easy as you suggested, you just picked the wrong file.
First you have to decide if you want to take the javaScript only or the jQuery implementation, 
so you chose the folders 'javascript_implememntation/' or 'jQuery_implementation/' where you find the file you want to use: either 'jsColorPicker.min.js' or 'jQueryColorPicker.min.js' (instead of 'colorPicker.js').
You don't need any CSS file as this is integrated.

Good luck,
Peter

**Comment by thednp** [comment]
I want to use the vanilla js, and it's pretty difficult. Maybe I don't understand the code, but in your examples you have several js files included, makes it pretty confusing.

I wish there was an example with ONE js file and initialization via inline scripting.

**Comment by PitPik** [comment]
Just take the example `javascript_implementation/index.html` and remove all `<script>` tags with the attribute `src="..."` except the last out commented one
```javascript
<script type="text/javascript" src="jsColorPicker.min.js"></script>
```
remove the comment tags and the demo will work.

This file (jsColorPicker.min.js) includes all other files: colors.js (that calculates color related stuff), colorPicker.data.js (that holds the HTML and CSS for the UI), colorPicker.js (the UI only) and jsColor.js (which is the implementation that makes colorPicker work on input fields, etc...)

**Comment by thednp** [comment]
Thank you, will do.

**Comment by PitPik** [comment]
@thednp 
have you been successful?

**Comment by thednp** [comment]
Sorry, I got busy with other stuff, I'll close this for now and re-open, only if I encounter problems.

Thank you so much.

**Comment by thednp** [comment]
@PitPik I finally managed to implement into my code, but it's gonna be the jQuery version.
