### ISSUE TITLE
Verticle Stretching on first use

### ISSUE THREAD

**Issue by ChadKeating** [PitPik/colorPicker#23]
So on the first use of the jquery implementation color picker it stretches vertically and then resizes. 
This only happens on firefox as far as I can tell.

This happens on your demo page also:

![Demo Page Issue](http://puu.sh/iq4h9/728baa5293.png)

Is it possible to stop this behavior somehow?

**Comment by PitPik** [comment]
Hi @ChadKeating,
wow, this is quite ugly, I agree. (Sorry btw. that I answer so late,... I was offline for quite a long time.
This issue might be caused by the css being included dynamically. If the browser is not fast enough then the css doesn't kick in fast enough, although I haven't seen this before (nor heard about this).
First, you could just place the css (wich you can fin in development/colorPicker.css) in the head of your document and I'll make a switch for the init options to be able to add the css on init.
I hope I can do this soon... ;o)
Check for updates in the future.
Cheers
Peter

**Comment by PitPik** [comment]
Fixed this in implementations (waiting for css to be loaded due to img.onload; quick-fix)
